name: my_messenger_app
description: A new Flutter project.

publish_to: 'none' # Этот проект не публикуется в pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Добавлено для локализации
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.14.0

  # Firebase Authentication
  firebase_auth: ^5.6.0

  # Cloud Firestore
  cloud_firestore: ^5.6.9

  # Дополнительные полезные пакеты
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3 # Убедитесь, что эта строка есть и версия актуальна (можно оставить ^2.0.15 или обновить до ^2.5.3)
  http: ^1.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
