// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1mpZguGHAvopSwowGL4NpoimDUkxAT2k',
    appId: '1:35816631802:web:d023a9e06189eccf570843',
    messagingSenderId: '35816631802',
    projectId: 'pixelgram-25f5f',
    authDomain: 'pixelgram-25f5f.firebaseapp.com',
    storageBucket: 'pixelgram-25f5f.firebasestorage.app',
    measurementId: 'G-9LL52J8H92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKID6lXK3i8EUuHy5R1J9uDuyDiy4wiy8',
    appId: '1:35816631802:android:97f6a8e0f7482c62570843',
    messagingSenderId: '35816631802',
    projectId: 'pixelgram-25f5f',
    storageBucket: 'pixelgram-25f5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFf8B0E7yTsDGc1Ezik3wy3eLVGESbwE8',
    appId: '1:35816631802:ios:54313ab69ef82430570843',
    messagingSenderId: '35816631802',
    projectId: 'pixelgram-25f5f',
    storageBucket: 'pixelgram-25f5f.firebasestorage.app',
    iosBundleId: 'com.example.myMessengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFf8B0E7yTsDGc1Ezik3wy3eLVGESbwE8',
    appId: '1:35816631802:ios:54313ab69ef82430570843',
    messagingSenderId: '35816631802',
    projectId: 'pixelgram-25f5f',
    storageBucket: 'pixelgram-25f5f.firebasestorage.app',
    iosBundleId: 'com.example.myMessengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1mpZguGHAvopSwowGL4NpoimDUkxAT2k',
    appId: '1:35816631802:web:4311ed2fa944155f570843',
    messagingSenderId: '35816631802',
    projectId: 'pixelgram-25f5f',
    authDomain: 'pixelgram-25f5f.firebaseapp.com',
    storageBucket: 'pixelgram-25f5f.firebasestorage.app',
    measurementId: 'G-F9KY6LNEPN',
  );

}